
```{r thurs2, include=FALSE}
library(tidyverse)
```

```{r thurs3, include=FALSE}
setwd("/Users/mczahor/Desktop/DaytoDay/Day 2 July 9")
savant <- read.csv("savant_data.csv")
ggplot(savant, aes(x = as.numeric(slg), 
                   y = as.numeric(woba),
                   )) + geom_point()+
  theme_bw()+
  xlab("SLG")+
  ylab("wOBA")

```


```{r thurs4}
try <- savant%>%filter(total_pitches>2000)%>%mutate(
        counts_cut_number   = cut_number(total_pitches, n = 4))

levels(try$counts_cut_number) <- c("1","2","3","4")

ggplot(try, aes(x = as.numeric(slg), 
                   y = as.numeric(woba),
                   col=counts_cut_number,
                   size=counts_cut_number
                   )) + geom_point()+
  theme_bw()+
  xlab("SLG")+
  ylab("wOBA")

```





```{r thurs5}
try <- savant%>%filter(total_pitches>____)%>%mutate(
        counts_cut_number   = cut_number(total_pitches, ____))

levels(try$counts_cut_number) <- c(_______)

ggplot(try, aes(x = as.numeric(slg), 
                   y = as.numeric(woba),
                   col=counts_cut_number,
                   size=counts_cut_number
                   )) + geom_point()+
  theme_bw()+
  xlab("____")+
  ylab("wOBA")

```


```{r thurs6}
ggplot(try, aes(x = as.numeric(slg), 
                   y = as.numeric(woba)
                   )) + geom_point(col="red")+
  theme_bw()+
  xlab("SLG")+
  ylab("wOBA")


ggplot(try, aes(x = as.numeric(slg), 
                   y = as.numeric(woba),
                   col=as.numeric(slg)
                   )) + geom_point()+
  theme_bw()+
  xlab("SLG")+
  ylab("wOBA")

```


```{r thurs7}
ggplot(data = try) +
geom_point(mapping = 
aes(x = counts_cut_number, 
y = as.numeric(slg)
))




ggplot(data = try) +
geom_boxplot(mapping = 
aes(x = counts_cut_number, 
y = as.numeric(slg)
))

```



```{r thurs8}
ggplot(data = try) +
geom_histogram(mapping = 
                 aes(x = total_pitches))

```

```{r thurs9}
ggplot(data = try) +
geom_density(mapping = aes(x = total_pitches,
                           col=counts_cut_number))

```


```{r thurs10}
ggplot(data = try) +
geom_bar(mapping = aes(x = counts_cut_number, 
                       fill = counts_cut_number))

```


```{r thurs11}
ggplot(data = try) +
geom_point(mapping = aes(
x = as.numeric(iso), 
y = as.numeric(babip))) +
geom_smooth(mapping = 
aes(x = as.numeric(iso), 
y = as.numeric(babip)))

```


```{r thurs12}
ggplot(data = try, mapping = aes(x = as.numeric(iso), 
                                 y = as.numeric(babip))) +
geom_point() +
geom_smooth()

```

```{r thurs13}
ggplot(data = try, mapping = aes(x = as.numeric(iso), 
                                 y = as.numeric(babip))) +
geom_point(col="red") +
geom_smooth()

```

```{r thurs14}
ggplot(data = try, mapping = aes(x = as.numeric(iso), 
                                 y = as.numeric(babip))) +
geom_point(col="red") +
geom_smooth(data=filter(try,counts_cut_number=="2"))
```

```{r thurs15}
ggplot(data = try) +
geom_boxplot(mapping = 
aes(x = counts_cut_number, 
y = as.numeric(slg)
))
```


```{r thurs16}
ggplot(data = try) +
geom_boxplot(mapping = 
aes(x = counts_cut_number, 
y = as.numeric(slg)
))
```

```{r thurs17}
ggplot(data = try, mapping = aes(x = as.numeric(iso), 
                                 y = as.numeric(babip))) +
geom_point() +
geom_smooth()
```

```{r thurs18}
ggplot(data = try,mapping = aes(x = counts_cut_number, y = as.numeric(slg))) +
geom_boxplot()+ stat_summary(geom = "point", y.fun = "mean", color = "blue", size = 3)
```

```{r thurs19}
ggplot(data = try, mapping = aes(x = as.numeric(iso), 
                                 y = as.numeric(babip))) +
geom_point(col="red") +
geom_smooth()
```

```{r thurs20}
ggplot(data = tibble(x = c(-20, 20)), aes(x = x)) +
stat_function(fun = dnorm, args = list(mean = 0, sd = 5), color = "black") +
stat_function(fun = dnorm, args = list(mean = 0, sd = 1), color = "red") +
stat_function(fun = dnorm, args = list(mean = 0, sd = 3), color = "blue")
```


```{r thurs21}
ggplot(try, aes(x = counts_cut_number, y = as.numeric(slg))) +
geom_point()

ggplot(try, aes(x = counts_cut_number, y = as.numeric(slg))) +
geom_point(position="jitter")

ggplot(try, aes(x = counts_cut_number, y = as.numeric(slg))) +
geom_point(position = position_jitter(width = 0.3, height = .1))

```


```{r thurs22}
try <- try%>%arrange(as.numeric(release_extension))%>%
  mutate(
        extend_group= cut_number(as.numeric(release_extension), n = 4)
        )

levels(try$extend_group) <- c("verylow","moderate","high","veryhigh")


ggplot(data = try, mapping = aes(x = counts_cut_number)) +
geom_bar(mapping = aes(fill = extend_group))

```


```{r thurs23}
ggplot(try, aes(x = counts_cut_number)) +
geom_bar(aes(fill = extend_group), position = "dodge")

```

```{r thurs24}
ggplot(data = try) +
geom_bar(mapping = aes(x = counts_cut_number, 
                       fill = counts_cut_number)) +
scale_fill_brewer(palette = "Dark2")

```

```{r thurs25}
ggplot(try, mapping = aes(x = as.numeric(woba), y = as.numeric(xwoba))) +
geom_point() +
scale_x_continuous(limits = c(.24,.4))
```


```{r thurs26}
ggplot(data = try) +
geom_point(mapping = aes(x = as.numeric(woba), 
                         y = as.numeric(xwoba), 
                         color = extend_group)) +
  facet_wrap(~ extend_group)

```

```{r thurs27}
ggplot(data = try) +
geom_point(mapping = aes(x = as.numeric(woba), 
                         y = as.numeric(xwoba), 
                         color = extend_group)) +
  facet_wrap(~ extend_group)+theme_bw()
```


```{r thurs28}
color_plot <- ggplot(data = try) +
geom_point(mapping = aes(x = as.numeric(woba), 
y = as.numeric(xwoba)))

ggsave("filename.png", plot = color_plot, width = 8, height = 6,
units = "in", dpi = "retina")

#or
#pdf(“filename.pdf”)
#Plotcode…….
#dev.off()

```


```{r thurs29}
setwd("/Users/mczahor/Desktop/DaytoDay/Day 2 July 9")

nba <- read.csv("nba_logreg.csv")
library(skimr)
skim(nba)
select(nba,Name)

```

```{r thurs30}
select(nba,Name, GP)
select(nba,GP:FGM)
select(nba,-c(GP,PTS))  
select(nba, starts_with("P"))
#ends_with
```



```{r thurs31}
select(nba,contains("T"))
select(nba,one_of(c("pts", "PTS")))
filter(nba,PTS>20)
nba%>%filter(Name=="Michael Jordan*")
```


```{r thurs32}
nba%>%filter(GP>55,PTS>17,TARGET_5Yrs==0)
```

```{r thurs33}
arrange(nba,GP)
```

```{r thurs34}
arrange(nba,GP,Name)%>%select(Name,GP)
```


```{r thurs35}
arrange(nba,GP,desc(Name))%>%
select(Name,GP)
```


```{r thurs36}
filter(nba,GP<16|GP>75)%>%
  arrange(Name)%>%
  select(GP,Name)
```

```{r thurs37}
filter(nba,GP<16|GP>75)%>%
  arrange(Name)%>%
  select(GP,Name)%>%
  ggplot(aes(x=GP))+geom_histogram()

```

```{r thurs38}
nba %>% 
  filter(GP>75)%>%
  summarize(meanpts = mean(PTS), 
            meanmin = mean(MIN))

```


```{r thurs39}
nba %>% summarize(n = n())
```

```{r thurs40}
nba %>% summarize(
n = n(), nGP = n_distinct(GP)
)
```

```{r thurs41}
nba %>%
  group_by(TARGET_5Yrs)%>%
  summarize(total = n())
```


```{r thurs42}
nba_small <- tribble(
~Name, ~Game, ~Pts,
"Michael Jordan", "1", 25,
"Michael Jordan", "7", 28,
"Kobe Bryant", "1", 26,
"Kobe Bryant", "7", 25,
"Lebron James", "1", 23,
"Lebron James", "7", 27
)

nba_small %>%
summarize(mean = mean(Pts), 
          sum = sum(Pts),
          n = n())

```

```{r thurs43}
nba_small %>%group_by(Name)%>%
summarize(mean = mean(Pts), 
          sum = sum(Pts),
          n = n())
```


```{r thurs44}
nba %>%
  group_by(TARGET_5Yrs)%>%
  summarize(total = n())
```


```{r thurs45}
nba %>%
filter(TARGET_5Yrs==1) %>%
group_by(Name)%>%
summarise(m_oreb = mean(OREB),
          m_dreb= mean(DREB)) %>%
arrange(desc(m_oreb))%>%
ungroup() %>%
slice(1:10) %>%
ggplot() +
geom_col(mapping = aes(x = Name, y = m_oreb,
fill = Name)) +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
labs(x = "name")
```

```{r thurs46}
nba %>%
  mutate(totmin=GP*MIN)%>%
  select(Name,totmin)

```


```{r thurs47}
install.packages('tidyverse')

install.packages("devtools")
devtools::install_github("meysubb/cfbscrapR")

remotes::install_github("rstudio/gt")

library(tidyverse)
library(cfbscrapR)
library(gt)


pbp_2019 <- data.frame()
for(i in 1:15){
  data <- cfb_pbp_data(year = 2019, season_type = "both", week = i, epa_wpa = TRUE) %>% mutate(week = i)
  df <- data.frame(data)
  pbp_2019 <- bind_rows(pbp_2019, df)
}

setwd("/Users/mczahor/Desktop")
write.csv(pbp_2019,"ncaa_cf_2019.csv")

setwd("/Users/mczahor/Desktop/DaytoDay/Day 2 July 9")
ncaa <- read.csv("ncaa_cf_2019.csv")
```

```{r thurs48}
skim(ncaa)
str(ncaa)
```

```{r thurs49}
ncaa%>%
  group_by(game_id)%>%
  summarise(perc_plays_sd=100*sum(drive_scoring)/n())
```

```{r thurs50}
da <- ncaa%>%filter(game_id==401110720)
ncaa$drive_result[1]
str_sub(ncaa$drive_result[1], start =1, end = 3)
```

```{r thurs51}
da$drive_result <- as.factor(da$drive_result)
levels(da$drive_result)
unclass(da$drive_result)
```

```{r thurs52}
ncaa %>%
drop_na(offense_conference) %>%
group_by(offense_conference) %>%
summarize(avgyds = mean(yards_gained)) %>%
ggplot(mapping = aes(x = avgyds, y = offense_conference)) +
geom_point()+theme_bw()
```


```{r thurs53}
ncaa %>%
drop_na(offense_conference) %>%
group_by(offense_conference) %>%
summarize(avgyds = mean(yards_gained)) %>%
ggplot(mapping = aes(x = avgyds, y = fct_reorder(offense_conference,avgyds,mean))) +
geom_point()+theme_bw()
```

```{r thurs54}
ncaa %>%drop_na(offense_conference) %>%
ggplot(aes(fct_infreq(offense_conference))) + geom_bar()

ncaa %>%drop_na(offense_conference) %>%
ggplot(aes(fct_rev(fct_infreq(offense_conference)))) + 
  geom_bar()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```


