
```{r thurs0, include=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(skimr)
library(devtools)


next_gen <- read.csv("next_gen_season.csv")
```


```{r thurs1}
skim(next_gen)
```

```{r thurs 2}
next_gen%>%
  ggplot(aes(x=completions,y=passYards))+
  geom_point()+
  geom_smooth(method="lm")
```


```{r thurs 3}

next_gen%>%
  ggplot(mapping=aes(x=avgAirDistance))+
  geom_histogram(binwidth=0.25)
```

```{r thurs 4}
lm(passYards ~ completions, data = next_gen)
```


```{r thurs 4}
lm(passYards ~ completions, data = next_gen)
```



```{r thurs5}
next_gen <- read.csv("next_gen_season.csv")
lm_examp <- next_gen%>%
  lm(passYards~completions,data=.)

par(mfrow=c(2,2))
plot(lm_examp)

```

```{r thurs 6}
library(broom)
summary(lm_examp)
lm_examp%>%tidy()
lm_examp%>%glance()
lm_examp%>%augment()
lm_examp%>%augment(data=next_gen)


next_gen%>%
  ggplot(mapping=aes(x=completions,y=passYards))+
  geom_point()+
  geom_smooth(method="lm")
```


```{r thurs7}
lm_examp %>%
glance() %>%
select(adj.r.squared, p.value)
```

```{r thurs 8}
lm_examp %>%
tidy() %>% filter(p.value < 0.05)
```

```{r thurs 9}
lm_examp2 <- next_gen%>%
  lm(passYards~completions+aggressiveness+as.factor(season),data=.)

lm_examp2 %>%
tidy()
```

```{r thurs10}
lm_examp %>%
augment(data = next_gen) %>%
ggplot(mapping = aes(x = completions, y = .fitted)) +
geom_point(mapping = aes(y =passYards ), alpha = 0.1) +
geom_line(color = "blue")
```


```{r thurs11}
lm_examp %>%
augment(data = next_gen) %>%
ggplot(mapping = aes(x = completions, y = .fitted)) +
geom_point(mapping = aes(y =passYards ), alpha = 0.8) +
geom_line(color = "blue")+facet_wrap(~as.factor(season))
```



```{r thurs 12}
library(modelr)
next_gen%>%
  add_predictions(lm_examp)%>%
  select(passYards,pred)
```


```{r thurs13}
next_gen %>% 
  spread_predictions(lm_examp, lm_examp2)%>%
  select(passYards,lm_examp,lm_examp2)
```

```{r thurs14}
next_gen%>% 
  gather_predictions(lm_examp, lm_examp2)%>%
  select(model,passYards,pred)%>%
  arrange(passYards)
                  
```

```{r thurs 15}

next_gen %>%
gather_predictions(lm_examp, lm_examp2) %>%
filter(playerName %in%  unique(next_gen$playerName)[1:5]) %>%
ggplot(mapping = aes(x = completions, y = pred, color = model)) +
geom_line() +
facet_grid(rows = vars(season), cols = vars(seasonType))



```


```{r thurs 16}
next_gen %>%
add_residuals(lm_examp) %>%
ggplot(mapping = aes(x = completions, y = resid)) +
geom_point()
```

```{r}
next_gen %>%
gather_residuals(lm_examp, lm_examp2) %>%
ggplot(mapping = aes(x = completions, y = resid)) +
geom_point() +
facet_wrap(vars(model))
```



```{r}
next_gen %>%
gather_residuals(lm_examp, lm_examp2) %>%
ggplot(mapping = aes(x = completions, y = resid)) +
geom_hex() +
scale_fill_viridis_c() +
facet_wrap(vars(model))
```
