--- 
title: "eZcZ FlexDashboard"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
#Please read through each step below. Your are going to build a dashboard, one step at a time. In this chunk I am calling the necessary libraries for you. NOTE look above, our output is flexdashboard and we have the--- runtime: shiny --- option! this very important


library(flexdashboard)
library(shinydashboard)
library(shiny)
library(kableExtra)
library(dplyr)
library(plotly)
library(DT)
library(ggplot2)

#Step 1#CLICK KNIT

#Step 2#uncomment the line below

#fifa <- read.csv("fifa.csv")

#now your data is available for use!!!! Keep in mind we are still in this setup chunk. Nothing is displaying in our dashboard below. 


#Step 3#BELOW THIS CHUNK copy and paste the following (remove the #hashtags)

#Input {.sidebar} 
#-----------------------
#```{r}

#```



#Step 4#okay now click knit.... you should have a sidebar on your #dashbaord!


#NOW WE HAVE DATA AND A SIDE BAR!!!!!! 
#LET's create options for a user to choose from.
#first let's have the option to filter by Nationality

#Step 5#uncommment the code below (keep it in this current chunk)

#selectInput("nationality",label="Nationality",
#             choices=unique(fifa$Nationality),selected="NULL")


#Step 6#click knit.. note if you want to be able to choose multiple #countries please put ",multiple=TRUE" inside of the select input #statement like this

##selectInput("nationality",label="Nationality",
#             choices=unique(fifa$Nationality),selected="NULL",
#              multiple=TRUE)

#A brief note on the different parts inside of the selectinput statement. The first "nationality" is what we will use to reference the users choice. Anytime we want to reference this we will type input$nationality ... let's try this by creating a reactive data frame. 

#Step 7# Uncomment the code below... leave it in this chunk!

#new_df <- reactive({
#          a <- fifa%>%
#                  filter(Nationality %in% input$nationality)
#
#})



#Notice, the above starts with a parentheses and a BRACKET. To reference this new dataframe new_df anywhere else in the dashboard we must put it inside of a reactive or render statement with PARENTHESES after , example new_df().

#Okay we have a data set...dynamic input...and a reactive dataframe....time to move down to ###Scatterplot in the chunk below


```


Column
-----------------------------------------------------------------------

### Chart A

```{r}

##Step 8## uncomment the code below ... note new_df() has parentheses and is inside a renderPlot statement...at this point you should be able to dynamically change the scatterplot


#renderPlot({
#  
#  newdf()%>%
#    ggplot(aes(x=SprintSpeed,y=Strength))+
#    geom_point()
#  
#})

#Step 9 --> change the code above to have a * facet by nationality * color by nationality * and fit a linear moadel to each plot, label each point with the player name (hint aes(text=Name))....*wrap this whole thing in ggplotly()...MAKE sure to change renderPlot to renderPlotly.See solution file if you're lost


#Step 10 --> change the Column below to a tabset Column by typing {.tabset} next to the word Column


#Step 11 click knit

#Step 12 imagine we want a table of the filtered data ... go to ###Nationality Info below
```

Column
-----------------------------------------------------------------------

### Chart B

```{r}
#Step 13 Uncomment this table

#renderDataTable({
#a <- datatable(new_df()%>%select(Name,Nationality,Club,Position), extensions = #'Buttons',editable = TRUE, options = list(
#    dom = 'Bfrtip',
#    buttons = c('copy', 'print','csv'),scrollY =TRUE,scrollX = TRUE, paging = F
#  ), rownames = F)
#a
#})
```

### Chart C

```{r}
#step 14 create a reactive density plot for sprint speed, facetted by Nationality. 


```
