---
title: "tuesday2"
author: "M.S.Czahor"
date: "7/14/2020"
ou---
title: "Slide Set 3 eZcZ "
author: "M.S.Czahor"
output: html_document
---

```{r libraries, include=FALSE}
library(maps)
library(cluster)
library(dplyr)
library(ggplot2)
```

```{r data, include=FALSE}
nba <- read.csv("nba_logreg.csv")
nba$TARGET_5Yrs <- as.factor(nba$TARGET_5Yrs)
nba <- nba%>%select(Name,PTS,REB,TARGET_5Yrs)
```

```{r view, include=FALSE}
head(nba)
nba <- nba[-which(duplicated(nba$Name)==TRUE),]
rownames(nba) <- nba$Name
```


```{r standardize, include=FALSE}
ccs=data.frame(sapply(nba[,-c(1,4)], scale)) 
##this scales each column of the data and makes a new data frame ccs
rownames(ccs)=rownames(nba) ##this makes sure the state names are in our standardized data set
head(ccs)
```


```{r}
install.packages("devtools")
library(devtools)
install_github("rtelmore/ballr")
library(ballr)
```

```{r}
#The clustering analysis uses the ballr package to access the per game statistics of players in the 2019 season 
#from https://www.basketball-reference.com/ 
library(ballr)
NBA <- NBAPerGameStatistics(season = 2019)
NBA <- NBA[, 8:28]
```


```{r}
factorial(N)
```

```{r}
choose(140,60)
```

```{r}
x <- 1:10

t <- function(x){
  1/2^(x)
}


barplot(t(x),las=1,names.arg = x)
```


```{r}
# exact
dbinom(x = 10, size = 18, prob = .6)


data.frame(heads = 0:18, prob = dbinom(x = 0:18, size = 18, prob = 0.6)) %>%
  mutate(Make = ifelse(heads == 2, "Miss", "Make")) %>%
ggplot(aes(x = factor(heads), y = prob, fill = Make)) +
  geom_col() +
  geom_text(
    aes(label = round(prob,2), y = prob + 0.01),
    position = position_dodge(0.9),
    size = 3,
    vjust = 0
  ) +
  labs(title = "Probability of X = 2 successes.",
       subtitle = "b(18, .6)",
       x = "Successes (x)",
       y = "probability") 


```


```{r}
library(dplyr)
library(ggplot2)

data.frame(heads = 0:15, 
           pmf = dbinom(x = 0:15, size = 15, prob = 0.6),
           cdf = pbinom(q = 0:15, size = 15, prob = 0.6, 
                        lower.tail = TRUE)) %>%
  mutate(Make = ifelse(heads <= 8, "<=8", "other")) %>%
ggplot(aes(x = factor(heads), y = cdf, fill = Make)) +
  geom_col() +
  geom_text(
    aes(label = round(cdf,2), y = cdf + 0.01),
    position = position_dodge(0.9),
    size = 3,
    vjust = 0
  ) +
  labs(title = "Probability of X <= 8 successes.",
       subtitle = "b(15, .6)",
       x = "Successes (x)",
       y = "probability") 

```


```{r}
runif(1)
```

```{r}
pnorm(1.5, mean=1.0,sd=2.0) ##find the probability N < 1.5 for a normal r.v. with mean=2.0 and standard deviation=2.0

1-pnorm(5, mean=0.0, sd=5.0)
```

```{r}

#exercise here
```

```{r}
fake.data<-rnorm(100) ##Generate 100 random numbers from the standard normal distribution

hist(fake.data)

IQR(fake.data)/sd(fake.data)

qqnorm(fake.data)
qqline(fake.data, col='red')
```


```{r}
fake.unif<-runif(100) 
##Generate 100 random numbers from the uniform distribution on [0,1]
hist(fake.unif)
IQR(fake.unif)/sd(fake.unif)
#This is not close to the target value of about  1.3
qqnorm(fake.unif)
qqline(fake.unif, col='red')
```


```{r}
install.packages("PerformanceAnalytics")
library(PerformanceAnalytics)

nba <- read.csv("nba_logreg.csv")

nba <- nba%>%select(MIN,PTS,FGA,X3PA,OREB,DREB,AST,STL,BLK)
chart.Correlation(nba, histogram=TRUE, pch=19)
```


```{r}
install.packages("DataExplorer")
library(DataExplorer)

plot_str(nba)
```


```{r}
plot_missing(nba)
```

```{r}
plot_histogram(nba)
```


```{r}
plot_density(nba)
```


```{r}
plot_correlation(nba, type = 'continuous')
```

```{r}
plot_bar(nba)
```

```{r}
create_report(nba)
```

```{r}
library(Lahman)
data( Teams )
data( Salaries )
str( Salaries )
```

```{r}
Salaries <- Salaries %>% 
  mutate( salary.adj = salary*(1.03)^( max(yearID) - yearID ) )

d2 <- Salaries %>%
            group_by( teamID, yearID, lgID ) %>%
            summarize( n.players=n(), adj.budget=sum(salary.adj) ) %>%
            merge( Teams, by=c( "yearID", "teamID", "lgID" ), all=FALSE) %>%
            filter( yearID >= 1900 )


ave.so <- d2$SO/d2$G

  #plot
ggplot(d2, aes(yearID, ave.so, color = name )) + 
  geom_path() +
  geom_point() +
  theme(legend.position = "none") +
  
  #animate
  labs(title = "Animated Lahman", x = 'Year', y = 'Avg. Strikeouts Per Game') +
  transition_reveal(along = yearID) +
  ease_aes('linear')
```