
```{r thurs1, include=FALSE}
library(swirl)
install_course_github("swirldev", "R_Programming_E")
swirl()
library(tidyverse)
library(skimr)
vb <- read.csv("vbdat.csv")
```

```{r thurs2, include=FALSE}
skim(vb)
```


```{r thurs3, include=FALSE}
function(){}  #() Inputs  #{} Computations
```

```{r thurs4, include=FALSE}
function(){}  #() Inputs  #{} Computations
```


```{r thurs5, include=FALSE}
Sys.Date
```

```{r thurs6, include=FALSE}
mean()
```

```{r thurs7, include=FALSE}
mean(c(1,2,3,4,100))
```


```{r thurs8, include=FALSE}
mean(c(1,2,3,4,100))
```


```{r thurs9, include=FALSE}
# You're about to write your first function! Just like you would assign a value 
# to a variable with the assignment operator, you assign functions in the following
# way:
#
# function_name <- function(arg1, arg2){
# # Manipulate arguments in some way
# # Return a value
# }
#
# The "variable name" you assign will become the name of your function. arg1 and
# arg2 represent the arguments of your function. You can manipulate the arguments
# you specify within the function. After sourcing the function, you can use the
# function by typing:
#
# function_name(value1, value2)
#
# Below we will create a function called boring_function. This function takes
# the argument `x` as input, and returns the value of x without modifying it.
# Delete the pound sign in front of the x to make the function work! Be sure to
# save this script and type submit() in the console after you make your changes.

boring_function <- function(x) {
#x}

```


```{r thurs 10}
boring_function('My first function!')
```

```{r thurs 11}
library(ggplot2)
ggplot2::geom_density2d
```

```{r thurs 12}
my_mean <- function(my_vector) {
  # Write your code here!
  # Remember: the last expression evaluated will be returned! 
}

vb$w_p1_age
```

```{r thurs 13}
# You're going to write a function called "remainder." remainder() will take
# two arguments: "num" and "divisor" where "num" is divided by "divisor" and
# the remainder is returned. Imagine that you usually want to know the remainder
# when you divide by 2, so set the default value of "divisor" to 2. Please be
# sure that "num" is the first argument and "divisor" is the second argument.
#
# Hint #1: You can use the modulus operator %% to find the remainder.
#  Ex: 7 %% 4 evaluates to 3.
#
# Remember to set appropriate default values! Be sure to save this
# script and type submit() in the console after you write the function.

remainder <- function(num, divisor) {
 # Write your code here!
 # Remember: the last expression evaluated will be returned!
}
```





```{r thurs14}
remainder <- function(num, divisor = 2) {
  num %% divisor
}

remainder(10,2)
```


```{r thurs15}
remainder(4, div=2)

```


```{r thurs15}
args(mean)

```


```{r thurs 16}
# You can pass functions as arguments to other functions just like you can pass
# data to functions. Let's say you define the following functions:
#
# add_two_numbers <- function(num1, num2){
#    num1 + num2
# }
#
# multiply_two_numbers <- function(num1, num2){
#	num1 * num2
# }
#
# some_function <- function(func){
#    func(2, 4)
# }
#
# As you can see we use the argument name "func" like a function inside of 
# "some_function()." By passing functions as arguments 
# some_function(add_two_numbers) will evaluate to 6, while
# some_function(multiply_two_numbers) will evaluate to 8.
# 
# Finish the function definition below so that if a function is passed into the
# "func" argument and some data (like a vector) is passed into the dat argument
# the evaluate() function will return the result of dat being passed as an
# argument to func.
#
# Hints: This exercise is a little tricky so I'll provide a few example of how
# evaluate() should act:
#    1. evaluate(sum, c(2, 4, 6)) should evaluate to 12
#    2. evaluate(median, c(7, 40, 9)) should evaluate to 9
#    3. evaluate(floor, 11.1) should evaluate to 11

evaluate <- function(func, dat){
  # Write your code here!
  # Remember: the last expression evaluated will be returned! 
}


```


```{r}
evaluate(function(x){x+1}, 9)
```

```{r}
evaluate(function(x){x+1}, c(8,3,2))
```


```{r}
paste( "The four major sports are", "baseball", "football", "hockey", "and basketball")
```

```{r}
telegram <- function(...){
  paste("START", ..., "STOP")
}
```



```{r}
mad_libs <- function(...){
  # Do your argument unpacking here!
  args <- list(...)
  qb <- args[["qb"]]
  rec <- args[["rec"]]
  opposition <- args[["opposition"]]
  
  # Don't modify any code below this comment.
  # Notice the variables you'll need to create in order for the code below to
  # be functional!
  paste("Today", qb, "threw for three touchdowns, two of them were caught by", rec, "who always plays well against the", opposition)
}

```


```{r}
# The syntax for creating new binary operators in R is unlike anything else in
# R, but it allows you to define a new syntax for your function. I would only
# recommend making your own binary operator if you plan on using it often!
#
# User-defined binary operators have the following syntax:
#      %[whatever]% 
# where [whatever] represents any valid variable name.
# 
# Let's say I wanted to define a binary operator that multiplied two numbers and
# then added one to the product. An implementation of that operator is below:
#
# "%mult_add_one%" <- function(left, right){ # Notice the quotation marks!
#   left * right + 1
# }
#
# I could then use this binary operator like `4 %mult_add_one% 5` which would
# evaluate to 21.
#
# Write your own binary operator below from absolute scratch! Your binary
# operator must be called %p% so that the expression:
#
#       "Good" %p% "job!"
#
# will evaluate to: "Good job!"

"%p%" <- function(){ # Remember to add arguments!
  
}

```


```{r}
"%p%" <- function(left, right){paste(left, right)
}

"%p%" <- function(left, right){ paste(left, right)
}
 "Tom Brady"%p%"now plays in Tampa."

```



```{r apply 1}
library(dplyr)
head(vb)
colnames(vb)
dim(vb)
```


```{r apply 2}
library(dplyr)
head(vb)
colnames(vb)
dim(vb)
class(vb)
```


```{r}
as.list(vb)
cls_list <- lapply(vb, class)
```

```{r}
as.character(cls_list)
```


```{r}
cls_vect <- sapply(vb, class)
```

```{r}
#34 - 65
sum(vb$w_p1_tot_attacks)
vb_counts <- vb[, 34:65]
```

```{r}
lapply(vb_counts,sum,na.rm=TRUE)
```

```{r}
sapply(vb_counts,sum,na.rm=TRUE)
sapply(vb_counts,mean,na.rm=TRUE)
```

```{r}
vb_c2 <-  vb[,34:37]
lapply(vb_c2,range,na.rm=TRUE)
sapply(vb_c2,range,na.rm=TRUE)

```

```{r}
#exercise
```

```{r}
lapply(unique_vals, function(elem) elem[2])
```

```{r sim}
 sample(1:6, 4, replace = TRUE)

```

```{r}
unique(vb$tournament)
#sample
sample(vb$tournament, 10)
```

```{r}
sample(LETTERS)
```

```{r}
matchup<- sample(c(0,1), 100, replace = TRUE, prob = c(0.7, 0.3))
```

```{r}
sum(matchup)
```

```{r}
?rbinom.
```

```{r}
rbinom(1, size = 100, prob = 0.3)

```

```{r}
rpois(5, 10)
```

```{r}
my_pois  <- replicate(100, rpois(5, 10))

```


```{r}
cm <- colMeans(my_pois)
hist(cm)
```
 
