
```{r thurs0, include=FALSE}
library(dplyr)
library(purrr)
library(ggplot2)
library(plotly)
library(skimr)
library(devtools)


fifa <- read.csv("fifa.csv")
```


```{r thurs1}
skim(fifa)
```


```{r thurs2}
fifa%>%
  ggplot(aes(x=Agility,y=SprintSpeed))+
  geom_point()
```


```{r thurs3}
mod <- fifa%>%
 lm(SprintSpeed~Agility,data=.)
View(mod)
```


```{r thurs4}
l_examp <- list(num = c(100, 200),
indic = TRUE,
cha = c("ez", "cz", "stats"))

l_examp["num"]
l_examp$num

```

```{r thurs5}
vec <- c(-2, -1, 0, 1, 2)
abs(vec)

lst <- list(-2,-1,0,1,2)
abs(list)
```

```{r thurs6}
set.seed(800)
scores <- list(
  player1 = round(rnorm(10,18,3)),
  player2 = round(rnorm(10,18,3)),
  player3 = round(rnorm(10,18,3)),
  player4 = round(rnorm(10,18,3)),
  player5 = round(rnorm(10,18,3))
)
scores
mean(scores)
```


```{r thurs7}
list(
   player1 = mean(scores$player1),
   player2 = mean(scores$player2),
   player3 = mean(scores$player3),
   player4 = mean(scores$player4),
   player5 = mean(scores$player5)
)
```


```{r thurs8}
library(purrr)
map(scores,mean)

scores%>%
  map(mean)
```


```{r thurs9}
scores%>%
  map(var)
```

```{r thurs10}
scores %>% map_dbl(mean)
scores %>% 
  map_dbl(quantile, prob = 0.75)
```

```{r thurs11}
scores %>%
map(length)%>%
map_lgl(all.equal, 10)
```


```{r thurs12}
scores %>%
map_dbl(max)
```



```{r thurs13}
vec <- scores$player1
(sum(vec) - min(vec)) / (length(vec) - 1)
```



```{r thurs14}

vec <- scores$player1
(sum(vec) - min(vec)) / (length(vec) - 1)
vec <- scores$player2
(sum(vec) - min(vec)) / (length(vec) - 1)
vec <- scores$player3
(sum(vec) - min(vec)) / (length(vec) - 1)
vec <- scores$player4
(sum(vec) - min(vec)) / (length(vec) - 1)
vec <- scores$player5
(sum(vec) - min(vec)) / (length(vec) - 1)
```


```{r thurs15}
vec <- scores[[1]]
adjust <- function(vec) {
(sum(vec) - min(vec)) / (length(vec) - 1)
}

adjust(scores[[2]])
```

```{r thurs16}
scores %>%
map_dbl(adjust)
```


```{r thurs17}
double_best <- function(x) {
(sum(x) + max(x)) / (length(x) + 1)
}

scores %>%
map_dbl(double_best)

```


```{r thurs18}
scores %>%
map_dbl(~ (sum(.x) + max(.x)) / (length(.x) + 1))
```


```{r thurs19}

ids <- fifa%>%
  group_by(Nationality)%>%
  summarise(ct=length(Nationality))%>%
  filter(ct>50)%>%
  select(Nationality)


library(tidyr)
obj <- fifa %>%
  filter(Nationality %in% ids$Nationality)%>%
group_by(Nationality) %>%
nest()


```



```{r thurs20}
fit_model <- function(df) lm(SprintSpeed ~ Agility, data = df)

obj_nested <- obj %>%
mutate(model = map(data, fit_model))


```


```{r thurs21}
library(broom)
library(modelr)
get_rsq <- function(mod) glance(mod)$r.squared
obj_nested <- obj_nested %>%
mutate(r.squared = map_dbl(model, get_rsq))

obj_nested
```

```{r thurs22}
nice_fit <- obj_nested%>%
  filter(r.squared>0.5)

nice_fit %>% unnest(data)
```

```{r thurs23}
unnest(nice_fit, data) %>%
ggplot(aes(x = Agility, y = SprintSpeed)) +
geom_line(aes(color = Nationality))
```


```{r thurs24}
library(rsample)
#bootstraps(data, times = 25, ...)
fifa%>%
  bootstraps(times=10)
```


```{r thurs25}
fifa %>%
bootstraps(times = 100) %>%
mutate(model = map(splits, function(x) lm(SprintSpeed ~ Agility, data = analysis(x))))
```

```{r thurs 26}
library(lubridate)

ymd(20101215)
mdy("4/1/17")
```



